### PR TITLE
Works with new influxdb 0.9 line protocol

### PR DESCRIPTION
**Pull request by kapilratnani**
It seems the due to different indent config the change looks huge. Let me know your config, i'll send a pull request again. Till then please review the code.

Thanx.

### CODE REVIEW

**Comment by tima** [comment]
Thanks for submitting a PR @kapilratnani. Not sure I follow you though. What's my config for formatting my code? That's probably best asked of @bernd who maintains the master I forked and then submitted my PR: https://github.com/bernd/statsd-influxdb-backend/pull/17. When I did that I made sure to keep the formatting in place and keep the diff as tight as can be.

**Comment by kapilratnani** [comment]
Thanx Tima, I'll send a pull request again later today. Need to refactor a bit and will keep the formatting in  place.

**Comment by bernd** [comment]
I am actually just using the plain Javascript formatting that Vim does. ;)

**Comment by bernd** [comment]
Don't worry too much about the formatting. If this works for you both, I can just merge it to my master and fix the formatting.

**Comment by kapilratnani** [comment]
Well, i am new to influxdb. Just figured out that this line protocol is quite new and it is not in the latest stable 0.9.0. It is supposed to come in >0.9.0. So, will just add another option in the config for version, refactor a bit and send a pull request again.

**Pull request closed without merging**
